name: CI/CD Tienda Perritos - Backend

on:
  push:
    branches: [ "master" ]

jobs:
  build-push-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    # 1. Configurar credenciales de AWS
    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 2. Login oficial en Amazon ECR
    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. Build imagen Backend y push a Amazon ECR
    - name: Build imagen Backend y push a Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tienda-backend
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    # 4. Registrar la nueva imagen en la Task Definition de ECS
    - name: Registrar la nueva imagen en la Task Definition de ECS
      id: render-web-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: tienda-backend
        image: ${{ steps.build-image.outputs.image }}

    # 5. Desplegar de manera nativa en Amazon ECS Fargate
    - name: Desplegar Definición de Tarea en Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-web-container.outputs.task-definition }}
        service: servicio-backend
        cluster: cluster-tienda-perrito
        wait-for-service-stability: true